name: CI and Dockerization

on:
  push:
    branches:
      - '*'

jobs:
  build_auth_and_event_management:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Clear project
        run: mvn clean

      - name: Compile the project
        run: mvn compile

      - name: Run test case
        run: mvn test

      - name: Build with Maven
        run: mvn clean install package

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: azizdhoukar  # ${{  DOCKER_USERNAME  }}
          password: dckr_pat_f4szj9gJ7kku6kw0Fl3zoReo_QA  # ${{  DOCKER_TOKEN  }}

      - name: Build Docker image
        run: docker build -t azizdhoukar/ps5:Booking .

      - name: Push Docker image to Docker Hub
        run: docker push azizdhoukar/ps5:Booking
